### ISSUE TITLE
Issue when running action multiple times in one job

### ISSUE THREAD

**Issue by giarc3** [IronCoreLabs/ironhide-actions#8]
Sometimes when running `decrypt@v3` multiple times in one job, you'll get an error `mv: cannot move 'ironhide-1.0.5-x86_64-unknown-linux-musl' to 'ironhide/ironhide-1.0.5-x86_64-unknown-linux-musl': Directory not empty`. Strangely, this doesn't happen every time.
The workaround is to decrypt all the files in a single step by putting the file names in a space-separated list as the input.
To fix we'll have to detect if the binary is already downloaded before trying to download/move a second time.

**Comment by skeet70** [comment]
Fix for this:

Make the unzip step `mv directory/ironhide* ironhide` (to catch `.exe`) instead of moving the directory. That will overwrite the file if it happens to be there. Make the decrypt step call `ironhide` instead of `ironhide/ironhide`.
